apiVersion: v1
kind: Service
metadata:
  name: blockchain-broker-service
spec:
  selector:
    app: blockchain-broker
  ports:
    - name: tpc
      port: 7331
      targetPort: 7331
      protocol: TCP
    - name: api
      port: 7332
      targetPort: 7332
  type: LoadBalancer
