apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-broker
  labels:
    app: blockchain-broker
spec:
  replicas: 1
  template:
    metadata:
      name: blockchain-broker
      labels:
        app: blockchain-broker
    spec:
      containers:
        - name: blockchain-broker
          image: blockchain-broker
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
          volumeMounts:
            - mountPath: /root/roteala
              name: broker-storage
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: broker-pvc
      restartPolicy: Always
  selector:
    matchLabels:
      app: blockchain-broker